#!/bin/bash

CXX=x86_64-w64-mingw32-gcc

pushd src &> /dev/null
$CXX main.c -lm -o ../exeWin ../externalWin.o -g -I../include -I../../SDL2/include -L../../SDL2/lib \
    -Bstatic -lmingw32 -lSDL2main -lSDL2 -Wall 
popd &> /dev/null
